version: '3.8'

services:
  # Service untuk Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: ardiartax_db
    restart: always
    environment:
      POSTGRES_USER: ardiartax
      POSTGRES_PASSWORD: bukankaumdajal666
      POSTGRES_DB: ardiartax_db
    ports:
      - "3030:5432" # Akses DB dari luar via port 3030
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service untuk Adminer (Database Management)
  adminer:
    image: adminer
    container_name: ardiartax_adminer
    restart: always
    ports:
      - "3031:8080" # Akses Adminer via port 3031
    depends_on:
      - db

volumes:
  postgres_data: