version: '3.8'

services:
  # Service 1: Backend FastAPI
  backend-ardiartax:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ardiartax_backend
    ports:
      - "3032:3032"
    env_file:
      - .env
    restart: always
    depends_on:
      - db-ardiartax # Memastikan database nyala lebih dulu sebelum backend berjalan

  # Service 2: PostgreSQL Database
  db-ardiartax:
    image: postgres:15-slim
    container_name: ardiartax_db
    restart: always
    environment:
      POSTGRES_USER: ardiartax
      POSTGRES_PASSWORD: bukankaumdajal666
      POSTGRES_DB: ardiartax_db
    ports:
      - "3030:5432" # Anda tetap bisa remote DB dari DBeaver/Navicat lewat port 3030 Mac Anda
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 3: Adminer (Database Web Management)
  adminer-ardiartax:
    image: adminer
    container_name: ardiartax_adminer
    restart: always
    ports:
      - "3031:8080" # Akses Adminer via browser di port 3031
    depends_on:
      - db-ardiartax

# DEFINISI VOLUMES: Wajib ada agar data PostgreSQL Anda persisten (tidak hilang)
volumes:
  postgres_data: