"""add group users

Revision ID: 2b0592fcbd7d
Revises: 9b6113b73e30
Create Date: 2026-05-18 21:02:56.322025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0592fcbd7d'
down_revision: Union[str, Sequence[str], None] = '9b6113b73e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Tambahkan kolom sebagai nullable=True dulu agar data lama tidak error
    op.add_column('documents', sa.Column('share_with_all', sa.Boolean(), nullable=True))
    
    # 2. Isi data lama yang bernilai NULL menjadi False
    op.execute("UPDATE documents SET share_with_all = FALSE WHERE share_with_all IS NULL")
    
    # 3. Ubah kolom menjadi NOT NULL setelah semua data lama terisi
    op.alter_column('documents', 'share_with_all', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    op.drop_column('documents', 'share_with_all')
    # ### end Alembic commands ###
