"""update peb (document number unique)

Revision ID: 841d727ff1d2
Revises: addc1490beab
Create Date: 2026-04-14 19:03:30.721738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841d727ff1d2'
down_revision: Union[str, Sequence[str], None] = 'addc1490beab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_number', 'peb', ['document_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_number', 'peb', type_='unique')
    # ### end Alembic commands ###
