"""update activity (delete start and finish progress)

Revision ID: 9158de0bf84b
Revises: ef47260b867b
Create Date: 2026-04-14 16:48:03.641299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9158de0bf84b'
down_revision: Union[str, Sequence[str], None] = 'ef47260b867b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'start_progress')
    op.drop_column('activities', 'finish_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('finish_progress', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('start_progress', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
