"""update peb (file name & path)

Revision ID: addc1490beab
Revises: b81e015181bb
Create Date: 2026-04-14 18:26:44.039743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addc1490beab'
down_revision: Union[str, Sequence[str], None] = 'b81e015181bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peb', sa.Column('file_path', sa.String(length=200), nullable=True))
    op.add_column('peb', sa.Column('file_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peb', 'file_name')
    op.drop_column('peb', 'file_path')
    # ### end Alembic commands ###
