"""update all

Revision ID: ca239956897d
Revises: ee6dbad473d4
Create Date: 2026-04-14 16:17:12.682216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca239956897d'
down_revision: Union[str, Sequence[str], None] = 'ee6dbad473d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('high', 'medium', 'low', name='activitycategory'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_progress', sa.DateTime(), nullable=True),
    sa.Column('finish_progress', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('peb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('buyer_address', sa.String(), nullable=True),
    sa.Column('document_number', sa.String(), nullable=True),
    sa.Column('document_date', sa.String(), nullable=True),
    sa.Column('invoice', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.String(), nullable=True),
    sa.Column('nilai_fob', sa.Float(), nullable=True),
    sa.Column('nilai_tukar', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peb_document_number'), 'peb', ['document_number'], unique=False)
    op.create_index(op.f('ix_peb_id'), 'peb', ['id'], unique=False)
    op.create_table('log_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'on_progress', 'cancel', 'done', name='activitystatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_activities_id'), 'log_activities', ['id'], unique=False)
    op.create_table('peb_terbit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peb_id', sa.Integer(), nullable=True),
    sa.Column('masa_terbit', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['peb_id'], ['peb.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('peb_id')
    )
    op.create_index(op.f('ix_peb_terbit_id'), 'peb_terbit', ['id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_peb_terbit_id'), table_name='peb_terbit')
    op.drop_table('peb_terbit')
    op.drop_index(op.f('ix_log_activities_id'), table_name='log_activities')
    op.drop_table('log_activities')
    op.drop_index(op.f('ix_peb_id'), table_name='peb')
    op.drop_index(op.f('ix_peb_document_number'), table_name='peb')
    op.drop_table('peb')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
